### PR TITLE
print command to stderr if running it fails

### PR DESCRIPTION
**Pull request by dirk-thomas**
This help in debugging when the command in launch file is not invokable.

Since the `_TaskException` is only used internally and not exposed anywhere I prefixed the name with underscore. Hope that makes sense.

### CODE REVIEW

**Comment by tfoote** [comment]
The _ seems ok to me. Though a doc block comment saying that this is only internal would be even less ambiguous.

**Comment by dirk-thomas** [comment]
PEP8 clearly define the semantic of a leading underscore (https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces). The docblock would be redundant - therefore I will leave it without.

**Comment by tfoote** [comment]
The leading underscore is typically used to indicate that it's for internal use. But according to the pep: "_single_leading_underscore : weak "internal use" indicator. E.g. from M import * does not import objects whose name starts with an underscore." Adding a doc block to any piece of code is rarely redundant. If it's worth a comment in the PR, it's probably worth a comment in the code, since someone reading the code at a later date will not likely find the comment in the PR.

**Comment by wjwwood** [comment]
@tfoote does this look ok otherwise (it seems you guys have agreed to disagree on the docstring note)?

**Comment by tfoote** [comment]
Yes, otherwise it looks good.

**Pull request merged**
