### PR TITLE
move launch files into launch.legacy namespace

### PR DESCRIPTION
**Pull request by wjwwood**
In preparation for opening pull requests for the new launch API I've been working on, this pull request (and the connected ones) will simply move the existing launch system into a sub package (called `legacy`) and updates anything using launch to also use this new API.

That way I can introduce the new API in smaller steps without first having to have it completely replace the existing tool and work in all cases.

This is the end goal, but there are a few things in `launch_testing` and a few of the output handlers I still need to port before I can start doing that. Plus this gives us something to compare and fallback to as we start using/tryout the new tool.

### CODE REVIEW

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4541/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1454/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3728/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4616/) (this is a "performance" test failure, and I think it's unrelated as nothing this test uses nor `rclpy` have been changed in these pr's)

**Comment by wjwwood** [comment]
This is ready for review.

**Comment by dirk-thomas** [comment]
Would the [history](https://github.com/ros2/launch/commits/refactor_launch_into_launch_legacy/launch/launch/legacy/exit_handler.py) be preserved if the move would be done in two steps: one commit just moving the file, another commit modifying the files? If yes, I would advocate for that.

**Comment by wjwwood** [comment]
Btw, the feature was requested but never went anywhere, but there is a chrome extension to help with it:

https://stackoverflow.com/questions/5646174/how-to-make-github-follow-directory-history-after-renames

**Comment by wjwwood** [comment]
I'll take the positive review to apply to the other pr's too since they're so automatically derivative. Thanks!

**Comment by dirk-thomas** [comment]
Was there a reason why the `launch_testing` module wasn't moved into a `legacy` namespace too? I am considering doing that now to "make room" for new testing logic as well as keep the API "symmetric".

**Comment by wjwwood** [comment]
No reason that’s fine for me.

**Pull request merged**
