### PR TITLE
[Eloquent backport] stop using constructors deprecated in pytest 5.4 (#391) Switch to from_parent (partial #421) avoid deprecation warning, use from_parent (#402)

### LINKED ISSUE #458: Eloquent Test failure caused by Deprecation warning?
## Bug report

**Required Info:**

- Operating System:
  - all
- Installation type:
  - nightlies
- Version or commit hash:
  - Eloquent
- DDS implementation:
  - all
- Client library (if applicable):
  - all

#### Steps to reproduce issue

https://ci.ros2.org/job/ci_linux/12231/console
* Eloquent repos file
* Target distro Eloquent
* OS Bionic
* Build up to launch_testing
* test only launch_testing

#### Expected behavior

All tests would pass

#### Actual behavior

```
Starting >>> launch_testing
10:31:04 ============================= test session starts ==============================
10:31:04 platform linux -- Python 3.6.9, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
10:31:04 cachedir: /home/jenkins-agent/workspace/ci_linux/ws/build/launch_testing/.pytest_cache
10:31:04 rootdir: /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/launch/launch_testing, configfile: pytest.ini, testpaths: test
10:31:04 plugins: launch-testing-0.9.6, ament-copyright-0.8.1, ament-pep257-0.8.1, ament-flake8-0.8.1, ament-lint-0.8.1, colcon-core-0.6.0, cov-2.10.1, rerunfailures-9.1, repeat-0.8.0, mock-3.3.1
10:31:04 collecting ... 
10:31:04 collected 0 items / 1 error                                                    
10:31:04 
10:31:04 ==================================== ERRORS ====================================
10:31:04 ________________________ ERROR collecting test session _________________________
10:31:04 ../../../../../venv/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__
10:31:05     return self._hookexec(self, self.get_hookimpls(), kwargs)
10:31:05 ../../../../../venv/lib/python3.6/site-packages/pluggy/manager.py:93: in _hookexec
10:31:05     return self._inner_hookexec(hook, methods, kwargs)
10:31:05 ../../../../../venv/lib/python3.6/site-packages/pluggy/manager.py:87: in <lambda>
10:31:05     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
10:31:05 ../../../../../venv/lib/python3.6/site-packages/_pytest/python.py:196: in pytest_collect_file
10:31:05     path=path, parent=parent
10:31:05 ../../../../../venv/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__
10:31:05     return self._hookexec(self, self.get_hookimpls(), kwargs)
10:31:05 ../../../../../venv/lib/python3.6/site-packages/pluggy/manager.py:93: in _hookexec
10:31:05     return self._inner_hookexec(hook, methods, kwargs)
10:31:05 ../../../../../venv/lib/python3.6/site-packages/pluggy/manager.py:87: in <lambda>
10:31:05     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
10:31:05 launch_testing/pytest/hooks.py:114: in pytest_pycollect_makemodule
10:31:05     return pytest.Module(path, parent)
10:31:05 ../../../../../venv/lib/python3.6/site-packages/_pytest/nodes.py:95: in __call__
10:31:05     warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
10:31:05 E   pytest.PytestDeprecationWarning: Direct construction of Module has been deprecated, please use Module.from_parent.
10:31:05 E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
10:31:05 - generated xml file: /home/jenkins-agent/workspace/ci_linux/ws/build/launch_testing/pytest.xml -
10:31:05 =========================== short test summary info ============================
10:31:05 ERROR  - pytest.PytestDeprecationWarning: Direct construction of Module has b...
10:31:05 !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
10:31:05 =============================== 1 error in 0.15s ===============================
10:31:05 Failed   <<< launch_testing [0.96s, exited with code 2]
10:31:05 
10:31:05 Summary: 0 packages finished [1.81s]
10:31:05   1 package failed: launch_testing
10:31:05 
10:31:05 II> colcon test returned: '2'
10:31:05 # END SUBSECTION
```

#### Additional information
Possibly would be fixed by backporting https://github.com/ros2/launch/pull/391 to ROS Eloquent

### PR DESCRIPTION
**Pull request by sloretz**
Cherry pick of #391 - checking if this fixes #458

Now also includes a cherry-pick of one commit from #421: f1c02f30e2bca3e461fb574df8e0694ee8d03f23

Now also includes a cherry-pick of #402

### CODE REVIEW

**Comment by sloretz** [comment]
Linux CI
[Build Status](https://ci.ros2.org/job/ci_linux/12232/)

**Comment by sloretz** [comment]
Linux CI after adding partial cherry-pick of #421 [Build Status](https://ci.ros2.org/job/ci_linux/12233/)

**Comment by sloretz** [comment]
Linux CI after adding cherry-pick of #402 [Build Status](https://ci.ros2.org/job/ci_linux/12234/)

**Comment by mjcarroll** [comment]
Supercedes #447

**Review by mjcarroll — APPROVED** [review]

**Comment by sloretz** [comment]
CI (build: `--packages-up-to launch_testing ros2action` test: `--packages-select launch_testing ros2action` ... picked ros2action since it's one of the packages that also showed this deprecation warning by using launch_testing)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12235/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7213/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9955/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12129/)

**Comment by sloretz** [comment]
CI including ros2/launch_ros#176 ( build: ` --packages-up-to launch_testing launch_testing_ros ros2action ros2interface ros2lifecycle ros2msg ros2node ros2pkg ros2service ros2srv ros2test ros2topic` test: `--packages-select launch_testing launch_testing_ros ros2action ros2interface ros2lifecycle ros2msg ros2node ros2pkg ros2service ros2srv ros2test ros2topic` ... that's all packages that are failing in the Eloquent nightlies)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12236/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7214/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9956/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12130/)

**Comment by sloretz** [comment]
CI looks ok, I think. There's no good build to compare the arm/OSX/Windows builds to, but none of the test failures appear related to this PR. The linux ones all seem to be an unrelated error: `AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'`, which might have to do with a mismatch in the version of `pycodestyle` and `flake8`: https://gitlab.com/pycqa/flake8/-/issues/427 ? There's also a couple pep257 test failures for existing doc strings.

**Pull request merged**
