### PR TITLE
[Eloquent] Fix parsing of cmd line arguments in XML and yaml file

### PR DESCRIPTION
**Pull request by ivanpauno**
Backports #379.
Fixes https://github.com/ros2/launch/issues/399.

### CODE REVIEW

**Comment by ivanpauno** [comment]
> LGTM and it does seem to break API in any way

The API was broken (i.e. not doing what intended), and this fixes it.
I can't imagine somebody using the old behavior intentionally for sth good.

**Comment by hidmic** [comment]
Argh, bad writing on my end.

**Comment by mjcarroll** [comment]
> I can't imagine somebody using the old behavior intentionally for sth good.

I agree, let's go ahead and get this in.

**Comment by ivanpauno** [comment]
Check is passing, and CI was run in the original PR.
Merging!

**Pull request merged**
