### PR TITLE
Added exec dependency on launch

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by esteve** [comment]
The tests for the examples pass now with `launch` added as an exec dependency:

http://ci.ros2.org/job/ros2_batch_ci_linux/615/
http://ci.ros2.org/job/ros2_batch_ci_osx/507/
http://ci.ros2.org/job/ros2_batch_ci_windows_opensplice/683/

**Comment by dirk-thomas** [comment]
+1

**Comment by dirk-thomas** [comment]
Shouldn't this be fixed? http://ci.ros2.org/job/ros2_batch_ci_linux/615/testReport/nose.failure/Failure/runTest/

**Comment by esteve** [comment]
Yes, that's weird. I didn't see that one, I just checked the overview and that test doesn't show up:

http://ci.ros2.org/job/ros2_batch_ci_linux/615/

I'll look into it, but I've run this locally both in isolation and not.

**Comment by dirk-thomas** [comment]
It is one of the 5 errors mentioned on that page. But jenkins will only show you links for the tests which have changed. Since this test failed before you have to look at the top of http://ci.ros2.org/job/ros2_batch_ci_linux/615/testReport/ to see all failing tests.

**Comment by esteve** [comment]
Yeah, I know, I just had a quick glance I didn't check more thoroughly.

**Comment by dirk-thomas** [comment]
The test also fails locally for me. Did you run the test locally? In isolation?

**Comment by esteve** [comment]
Yes, I did and in isolation :smile: 

> I'll look into it, but I've run this locally both in isolation and not.

**Comment by dirk-thomas** [comment]
Maybe you sourced the install space before running the tests in the same shell?

**Comment by esteve** [comment]
So, I wiped out the workspace, made sure I hadn't sourced the install space, etc. and ran the following:

```
$ src/ament/ament_tools/scripts/ament.py build --build-tests --isolated
$ src/ament/ament_tools/scripts/ament.py test --isolated
```

I can't seem to get the tests to fail, want us to take a look at it together?

**Comment by dirk-thomas** [comment]
I added the missing test dependency to fix the failing test: 7857c91eedb5ba10b083ead0ae977e00f3822836

**Comment by esteve** [comment]
Thanks!

**Pull request merged**
