### PR TITLE
Add conditional substitution

### LINKED ISSUE #727: Parse arguments into their relevant type
#### Feature description
Substitutions are meant to provide values for a dynamic launch configuration and thus they evaluate to strings. Substitutions though are also used to execute code (see PythonExpression). When that's performed, the result of a substitution must be wrapped in quotes as it needs to be defined as a string, and then it is compared to other strings. For example

```python
PythonExpression(["'value1' if '", LaunchConfiguration("name"), "' == 'true' else 'value2'"])
```

That's a primitive and cumbersome way of working with arguments. It would be useful if it was possible for the launch configurations to be parsed into the relevant type of their argument.

#### Implementation considerations
We could hopefully have specialized launch configurations, `{Bool,Int,Float,etc}LaunchConfiguration`, that parse their value before returning it. Then, an expression like the above would become

```python
PythonExpression(["'value1' if ", BoolLaunchConfiguration("name"), " else 'value2'"])
```

Do you think that's reasonable and would you be interested in a PR?

### PR DESCRIPTION
**Pull request by nlamprian**
Closes #727

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
This looks fantastic to me, thanks for a nice clean pull request.  I'll run CI on it next.

**Review by clalancette — CHANGES_REQUESTED** [review]
@nlamprian It looks like flake8 is unhappy here, mostly about double quotes but also about some import order stuff.  I don't know why the Rpr job didn't pick up on it, but if you setup your workspace locally it should show it to you.  That will need to be fixed before we merge this, thanks.

**Comment by nlamprian** [comment]
Fixed, allegedly.
I did run the tests successfully last time. I am not able to reproduce the errors.
I am working on a fresh ros:rolling-ros-core container. I haven't identified what's different from the logs.

**Comment by clalancette** [comment]
> Fixed, allegedly. I did run the tests successfully last time. I am not able to reproduce the errors. I am working on a fresh ros:rolling-ros-core container. I haven't identified what's different from the logs.

Out of curiosity, what does `pip3 list | grep flake8` in the container show you?

**Comment by clalancette** [comment]
Locally I'm still seeing:

```
_________________________________ test_flake8 __________________________________
test/test_flake8.py:23: in test_flake8
    assert rc == 0, \
E   AssertionError: Found 1 code style errors / warnings:
E     ./launch/substitutions/if_else_substitution.py:27:1: I100 Import statements are in the wrong order. 'from .substitution_failure import SubstitutionFailure' should be before 'from ..utilities import perform_substitutions'
E   assert 1 == 0
```

**Comment by nlamprian** [comment]
```
root@nlamprian:~/ros_ws# pip3 list | grep flake8
ament-flake8                         0.15.2
flake8                               4.0.1
```

The last error is hopefully fixed (the message can be misinterpreted).

**Comment by clalancette** [comment]
> ```
> root@nlamprian:~/ros_ws# pip3 list | grep flake8
> ament-flake8                         0.15.2
> flake8                               4.0.1
> ```

OK, yeah.  You are missing a bunch of plugins, and flake8 is a bit annoying in that you can't specify which ones are required; it only runs the plugins you have installed.  My list looks like this:

```
ament-flake8                         0.15.2
flake8                               4.0.1
flake8-blind-except                  0.2.0
flake8-builtins                      1.5.3
flake8-class-newline                 1.6.0
flake8-comprehensions                3.8.0
flake8-deprecated                    1.3
flake8-docstrings                    1.6.0
flake8-import-order                  0.18.1
flake8-quotes                        3.3.1
```

We have a long-term plan to fix this up by making those plugins hard requirements, but we aren't there today.

Anyway, this looks good to me now (verified locally), so I'll run CI on this again.  Thanks for iterating.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19514/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14032/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20233/)

**Comment by federicociresola** [comment]
is it possible to include this feature also in the Humble branch?

**Pull request merged**
