### PR TITLE
Add UnregisterEventHandler action (#110)

### LINKED ISSUE #110: [launch] add new Action called UnregisterEventHandler
Without an action `UnregisterEventHandler` you have to use an `OpaqueFunction` and the `LaunchContext` to manually unregister an event handler, which is not introspectable.

### PR DESCRIPTION
**Pull request by jacobperron**
Closes #110
Also added tests for RegisterEventHandler and UnregisterEventHandler actions.

### CODE REVIEW

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5214/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1977/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4335/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5193/)

**Comment by dhood** [comment]
Could you check (if you haven't already) that modifying the snippet in https://github.com/ros2/launch/issues/90#issuecomment-400855418 to use the `UnregisterEventHandler` instead of the `OpaqueFunction` works as expected?

(would you be able to output the introspection output of the modified snippet too)

**Comment by wjwwood** [comment]
@dhood specifically the part of one of the opaque functions that uses `context.unregister_event_handler`, but the other one needs to stay for now.

**Comment by jacobperron** [comment]
I've updated https://github.com/ros2/launch/issues/90#issuecomment-400855418 to use `UnregisteredEventHandler` instead and it seems to behave the same as the original. I've also added a line for introspection.

Here is the snippet:

```python
from launch import LaunchDescription, LaunchIntrospector
import launch
import launch.actions
import launch.events
import launch_ros.actions
import launch_ros.events
import launch_ros.events.lifecycle

import lifecycle_msgs.msg


def generate_launch_description():
    lifecycle_talker = launch_ros.actions.LifecycleNode(
        node_name='talker', package='lifecycle', node_executable='lifecycle_talker', output='screen')

    lifecycle_listener_factory = launch.actions.OpaqueFunction(function=lambda context: [
        launch_ros.actions.LifecycleNode(
            node_name='listener', package='lifecycle', node_executable='lifecycle_listener',
            output='screen')
    ])

    # When the talker reaches the 'inactive' state, make it take the 'activate' transition
    def on_talker_reaches_inactive(context):
        nonlocal on_talker_transitions_to_inactive_event_handler
        return [
            # comment this line if you want a new listener everytime
            launch.actions.UnregisterEventHandler(on_talker_transitions_to_inactive_event_handler),
            launch.actions.EmitEvent(event=launch_ros.events.lifecycle.ChangeState(
                lifecycle_node_matcher=launch.events.process.matches_action(lifecycle_talker),
                transition_id=lifecycle_msgs.msg.Transition.TRANSITION_ACTIVATE,
            )),
        ]

    on_talker_transitions_to_inactive_event_handler = launch_ros.event_handlers.OnStateTransition(
        target_lifecycle_node=lifecycle_talker, goal_state='inactive',
        entities=[
            launch.actions.LogInfo(
                msg="node 'talker' reached the 'inactive' state, 'activating'."),
            launch.actions.OpaqueFunction(function=on_talker_reaches_inactive),
        ],
    )
    register_event_handler_for_talker_reaches_inactive_state = launch.actions.RegisterEventHandler(
        on_talker_transitions_to_inactive_event_handler
    )

    # When the talker node reaches the 'active' state, log a message and start the listener node.
    register_event_handler_for_talker_reaches_active_state = launch.actions.RegisterEventHandler(
        launch_ros.event_handlers.OnStateTransition(
            target_lifecycle_node=lifecycle_talker, goal_state='active',
            entities=[
                launch.actions.LogInfo(
                    msg="node 'talker' reached the 'active' state, launching 'listener'."),
                lifecycle_listener_factory,
            ],
        )
    )

    # Make the talker node take the 'configure' transition.
    emit_event_to_request_that_talker_does_configure_transition = launch.actions.EmitEvent(
        event=launch_ros.events.lifecycle.ChangeState(
            lifecycle_node_matcher=launch.events.process.matches_action(lifecycle_talker),
            transition_id=lifecycle_msgs.msg.Transition.TRANSITION_CONFIGURE,
        )
    )

    ld = LaunchDescription([
             register_event_handler_for_talker_reaches_inactive_state,
             register_event_handler_for_talker_reaches_active_state,
             lifecycle_talker,
             emit_event_to_request_that_talker_does_configure_transition
         ])

    print(LaunchIntrospector().format_launch_description(ld))

    """Launch a talker and a listener."""
    return ld
```

And the output of the introspection:

```sh
<launch.launch_description.LaunchDescription object at 0x7f71e1143be0>
├── RegisterEventHandler('<launch_ros.event_handlers.on_state_transition.OnStateTransition object at 0x7f71e1143a20>'):
│   ├── OnStateTransition(matcher='event == StateTransition and event.action == LifecycleNode(0x7f71e1130c50)', handler=<actions>)
│       ├── LogInfo('node 'talker' reached the 'inactive' state, 'activating'.')
│       └── Action('<launch.actions.opaque_function.OpaqueFunction object at 0x7f71e11439e8>')
├── RegisterEventHandler('<launch_ros.event_handlers.on_state_transition.OnStateTransition object at 0x7f71e1143b00>'):
│   ├── OnStateTransition(matcher='event == StateTransition and event.action == LifecycleNode(0x7f71e1130c50)', handler=<actions>)
│       ├── LogInfo('node 'talker' reached the 'active' state, launching 'listener'.')
│       └── Action('<launch.actions.opaque_function.OpaqueFunction object at 0x7f71e1143940>')
├── ExecuteProcess(cmd=[ExecInPkg(pkg='lifecycle', exec='lifecycle_talker'), LocalVar('node name')], cwd=None, env=None, shell=False)
└── EmitEvent(event='launch_ros.events.lifecycle.ChangeState')
```

**Pull request merged**
