### PR TITLE
Foxy backport: Add respawn and respawn_delay support (#426)

### PR DESCRIPTION
**Pull request by blacksoul000**
Signed-off-by: Chen Lihui <lihui.chen@sony.com>
Signed-off-by: Ivan Santiago Paunovic <ivanpauno@ekumenlabs.com>
Co-authored-by: Michel Hidalgo <michel@ekumenlabs.com>
Co-authored-by: Ivan Santiago Paunovic <ivanpauno@ekumenlabs.com>

### CODE REVIEW

**Comment by hidmic** [comment]
CI up to `launch` and `test_launch_ros`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13608/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8490/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11324/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13668/)

**Review by hidmic — APPROVED** [review]
LGTM pending green CI. @jacobperron thoughts?

**Comment by jacobperron** [comment]
SGTM :+1: It doesn't change the default behavior is Foxy.

**Review by jacobperron — APPROVED** [review]
pending CI

**Comment by hidmic** [comment]
Windows CI warnings are unrelated.

**Pull request merged**
