### PR TITLE
Backport error message improvements

### PR DESCRIPTION
**Pull request by dyackzan**
backport https://github.com/ros2/launch/pull/626 and https://github.com/ros2/launch/pull/753

### CODE REVIEW

**Comment by dyackzan** [comment]
@tylerjw @clalancette here's the backport as discussed in https://github.com/ros2/launch/pull/753#issuecomment-1908765480

**Review by tylerjw — APPROVED** [review]
I tested this locally and it seems to work. Thank you for making the backport.

**Comment by clalancette** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20211/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14631/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20932/)

**Review by mjcarroll — APPROVED** [review]
LGTM with Green CI

**Pull request merged**
