### PR TITLE
Prepare 0.8.5

### PR DESCRIPTION
**Pull request by hidmic**
Ready for Dashing patch release 3. I'll tag and `bloom-release` once this is merged.

### CODE REVIEW

**Comment by hidmic** [comment]
Thanks Github for the default `Squash-merge`... -.-

**Comment by hidmic** [comment]
@nuclearsandwich should I revert or push-force to keep commits messages clean? Sorry :(

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich should I revert or push-force to keep commit messages clean? Sorry :(

That's a @wjwwood question. I would opt for force pushing but I don't care overmuch.

**Comment by wjwwood** [comment]
I don't mind either way. Rewriting it to be 0.8.5 or just doing an empty commit with the message `0.8.5` would be fine too.

**Comment by hidmic** [comment]
Branch rewritten!

**Pull request merged**
