### PR TITLE
Revert "Validate unparsed attributes and subentities in launch_xml and launch_yaml (#468) (#567)"

### PR DESCRIPTION
**Pull request by jacobperron**
Revert #567 because it breaks behavior in Foxy.

### CODE REVIEW

**Comment by jacobperron** [comment]
Proposing this revert as a fix to https://github.com/ros2/ros2/issues/1244

**Review by adityapande-1995 — APPROVED** [review]

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16228/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10853/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16583/)

**Comment by jacobperron** [comment]
Holding until we resolve discussion on what to do in https://github.com/ros2/ros2/issues/1244

**Comment by jacobperron** [comment]
Closing in favor of implementing https://github.com/ros2/launch/issues/597 and backporting to Foxy.

**Pull request closed without merging**
