### PR TITLE
[backport] Drop unused data_files entry for example_processes (#680)

### PR DESCRIPTION
**Pull request by xueying4402**

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21479/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15765/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/978/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22196/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
do you mind to sign the commit ?

**Review by fujitatomoya — APPROVED** [review]
lgtm (backport of https://github.com/ros2/launch/pull/680)

i think humble support RHEL 8 (not 9, that probably because RHEL CI failed)

* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1017/)

**Comment by ahcorde** [comment]
friendly ping @xueying4402

**Comment by xueying4402** [comment]
@ahcorde Thank you for pointing out the need for a sign-off. I want to clarify that this PR is a cherry-pick of a security-related commit from other branch, and I did not make any modifications to it. If there is a compliant way for me to add the sign-off information, I am happy to do so. (I have made an effort to find an appropriate method to add the sign-off, but unfortunately, I couldn't find one. )

Additionally, I had previously emailed regarding this matter but hadn't received a response. If there are any other adjustments needed, please let me know.

**Comment by clalancette** [comment]
I'm going to side-step the whole issue here by closing this, and then asking the bot to backport #680 instead.

**Pull request closed without merging**
