### PR TITLE
Add support for custom launch log file handling

### LINKED ISSUE #230: options to rotate log files
There should be options to rotate the log files based on either of the following criteria:

* maximum size of a log file (e.g. 100MB)
* maximum duration of a log file (e.g. 24h)

### PR DESCRIPTION
**Pull request by hidmic**
Closes #230 by generalizing logging handlers' setup, as it makes it much more flexible.

### CODE REVIEW

**Comment by hidmic** [comment]
Running CI (packages up to `test_communication`):

* Linux [Build Status](https://ci.ros2.org/job/ci_linux/7052/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3284/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5780/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6872/)

**Comment by hidmic** [comment]
Awesome! Thanks for the prompt review @wjwwood, going in.

**Comment by hidmic** [comment]
Alright, CI test failures are unrelated. Merging!

**Comment by rrai10** [comment]
Hey @hidmic, I hope you are doing well.

I am new to ros2 and in my case, I am having logs in .ros/log location. I want to achieve a log rotation at **midnight** for all the logs in this folder.  Every day should start with a new ros log file. Could you please suggest how I can achieve this?

**Pull request merged**
