### PR TITLE
Foxy backport Add arg_choice arg to DeclareLaunchArguments(#483)

### PR DESCRIPTION
**Pull request by v-lopez**
* Add arg_choice arg to DeclareLaunchArguments

Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>

* Apply suggestions from code review

Co-authored-by: Michel Hidalgo <michel@ekumenlabs.com>
Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>

* Error if provided choices is empty list

Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>

* Apply PR suggestions

Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>

* More quote fixing

Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>

Co-authored-by: Michel Hidalgo <michel@ekumenlabs.com>

### CODE REVIEW

**Comment by v-lopez** [comment]
@hidmic could we merge this? It is a direct cherry-pick from #483

**Review by hidmic — APPROVED** [review]
Thanks for the bump @v-lopez. LGTM !

Foxy CI up to `launch`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13704/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8579/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11418/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13775/)

@jacobperron thoughts?

**Comment by jacobperron** [comment]
Seems okay to me; I didn't look closely at the code.

**Comment by hidmic** [comment]
Re-running Windows CI:

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13809/)

**Comment by hidmic** [comment]
Alright. CI's green. Going in!

Thanks for your contribution and your patience @v-lopez.

**Comment by v-lopez** [comment]
Thanks for accepting it, would you have an ETA for the release of a version in foxy with these changes?

**Pull request merged**
