### PR TITLE
expose sigterm_timeout and sigkill_timeout to frontend

### PR DESCRIPTION
**Pull request by wjwwood**
Previously, these options were not accessible to the frontends like XML.

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
LGTM!
Though I guess we want to merge this after we branch off Humble.

It would also be nice to add some test cases.

**Comment by hidmic** [comment]
> It would also be nice to add some test cases.

+1 to adding some tests

**Comment by wjwwood** [comment]
How do you guys recommend I test it in `launch`? I was going to use some XML snippet to test it, but I don't have `launch_xml` or others available at that point. I don't see any other tests in `launch` that do something like this yet. Do you guys know of some?

**Comment by hidmic** [comment]
@wjwwood yeah, frontend tests for entities are in frontend packages right now (e.g. [here](https://github.com/ros2/launch/blob/master/launch_xml/test/launch_xml/test_executable.py)). 

Arguably, that's not very nice. It's not even necessary. I guess it was easy at the time (easier than building markup-agnostic testing infrastructure).

**Comment by wjwwood** [comment]
I can just add some tests there. But (for time travelers from the future) it would make sense to move the testing of these "exposures" into `launch` and being XML/YAML agnostic some how.

**Comment by hidmic** [comment]
@wjwwood do you still want to add some tests and merge this?

**Comment by wjwwood** [comment]
I would like to, but it's just been sitting in my open tabs waiting for me to have some time to do it.

**Comment by adityapande-1995** [comment]
Closing this in favour of https://github.com/ros2/launch/pull/667

**Pull request closed without merging**
