### PR TITLE
[Foxy] Allow configuring logging directory through environment variables.

### PR DESCRIPTION
**Pull request by tgreier**
Backport to Foxy PR #460.

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
I'm OK with this, @jacobperron ? 

@tgreier it'd be great if you can just cherry-pick #460's squashed commit so as to keep the original author in here.

**Comment by tgreier** [comment]
> it'd be great if you can just cherry-pick #460's squashed commit so as to keep the original author in here.

I thought that is what I did. I cherry-picked the merge commit to master from Oct 13. I am indeed new to cherry-picking and back-porting. What did I miss? I would be happy to fix.

**Comment by hidmic** [comment]
@tgreier did you let `git cherry-pick` do the commit? If not, that may explain why the original author is gone.

**Comment by tgreier** [comment]
> @tgreier did you let `git cherry-pick` do the commit? If not, that may explain why the original author is gone.

I did not. I was worried about just letting it go directly to commit. Is there a way for me to fix that now, or do I need to redo?

**Comment by hidmic** [comment]
@tgreier You can locally reset, cherry-pick, and force push.

**Review by hidmic — APPROVED** [review]
Perfect! Running CI up to `launch`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13318/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8248/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11048/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13359/)

@jacobperron thoughts?

**Comment by jacobperron** [comment]
The change okay to me :+1:  @tgreier Thanks for iterating on a backport!

**Comment by hidmic** [comment]
Windows warnings are unrelated. Merging. Thanks @tgreier !

**Pull request merged**
