### PR TITLE
add format overriding by environment variables

### PR DESCRIPTION
**Pull request by SammyRamone**
This is a proposed fix for https://github.com/ros2/launch_ros/issues/368
Originally, I planned on reusing the `RCUTILS_CONSOLE_OUTPUT_FORMAT` environment variable for this. Hoewever, this is not possible since launch and rcutils rely on two different logging implementations which have different names for the same things. For example one supports {line_number} and the other {lineno}. Instead I added two environment variables `OVERRIDE_LAUNCH_SCREEN_FORMAT` and `OVERRIDE_LAUNCH_LOG_FORMAT` since screen and log formatting is handled differently in the code.
I also framed the variables as override similar to https://github.com/ros2/launch/pull/713

Any feedback is welcome.

### CODE REVIEW

**Comment by SammyRamone** [comment]
friendly ping @adityapande-1995 @methylDragon @wjwwood

**Review by methylDragon — CHANGES_REQUESTED** [review]
Heya, thanks for the contribution! I'm not in principle opposed to this, but could you add a test to the logging test for this? That would help prevent regressions!

https://github.com/ros2/launch/blob/cef1ce3217cd39e339bbaa8c62d8868392fbcba0/launch/test/launch/test_logging.py

**Comment by SammyRamone** [comment]
Sorry for the long wait. This was fairly low-priority for me and I only now had time to work on it again.
I added a test for the environment variables and also ensured that the other tests don't fail if the environment variable is set in the terminal in which the tests are executed.

**Comment by SammyRamone** [comment]
I also added a draft PR for documenting this PR https://github.com/ros2/ros2_documentation/pull/4061

**Comment by SammyRamone** [comment]
friendly ping @methylDragon

**Review by adityapande-1995 — APPROVED** [review]

**Comment by adityapande-1995** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20156/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14594/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20871/)

**Comment by dhood** [comment]
in case someone else is checking: as of jan 30 2024 this is released into jazzy, is not in humble. great feature, btw @SammyRamone !! would have been just what I was looking for! :+1: (but alas I'm on humble)

**Comment by gordon-n-stevenson** [comment]
Any chance of a https://github.com/Mergifyio backport humble ?

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble

**Pull request merged**
