### PR TITLE
Drop legacy launch package

### PR DESCRIPTION
**Pull request by hidmic**
Follow up after #167. Drops legacy launch code entirely. 

Signed-off-by: Michel Hidalgo <michel@ekumenlabs.com>

### CODE REVIEW

**Comment by hidmic** [comment]
Running CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6303/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2719/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5178/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6140/)

**Comment by hidmic** [comment]
@wjwwood tests failures are unrelated.

**Comment by dirk-thomas** [comment]
Please add information about this to the migration section of the Dashing release page.

**Comment by hidmic** [comment]
@dirk-thomas where's that section? Or should I add one?

**Comment by hidmic** [comment]
Any objection to get this one merged? It looks like `test_cli` test failures are still an issue (@sloretz correct?), thus CI will come out unstable again.

**Comment by mjcarroll** [comment]
No complaints from me.

**Comment by dirk-thomas** [comment]
> > Please add information about this to the migration section of the Dashing release page.

> where's that section?

https://index.ros.org/doc/ros2/Releases/Release-Dashing-Diademata/#changes-since-the-crystal-release

**Pull request merged**
