### PR TITLE
Update apex rostest

### PR DESCRIPTION
**Pull request by hidmic**
Brings in latest improvements in `apex_rostest`, primarily test parameterization support.

cc @pbaughman for awareness.

### CODE REVIEW

**Comment by wjwwood** [comment]
@hidmic What do you need me to do here?

**Comment by hidmic** [comment]
> What do you need me to do here?

I just tagged you as reviewer in both PRs.

I was waiting for the actual PRs to pass CI to merge this, but we can move forward now. Thoughts?

**Comment by wjwwood** [comment]
> I just tagged you as reviewer in both PRs.

Actually you assigned it to me in both cases, that's what I was curious about. also, this already has my approved review.

Feel free to merge it if you have a review and green CI.

**Comment by hidmic** [comment]
CI (full run):

* Linux [Build Status](https://ci.ros2.org/job/ci_linux/6709/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3023/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5512/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6538/)

**Comment by hidmic** [comment]
Test failures are unrelated and the failing job is a known issue. Merging!

**Pull request merged**
